services:
  - type: web
    name: telegram-gpt-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python gpt_bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        value: "8174692504:AAGwOdZ7KHBEL9nZh9ldWGs2ROnJt0qqJOM"
      - key: OPENAI_API_KEY
        value: "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"
